version: "3.7"

services:
  db:
    image: postgres:14.4
    container_name: vue3-training-db
    environment:
      POSTGRES_PASSWORD: "#vue3TrainingDb#"
    ports:
      - 55432:5432
    tty: true
    restart: always
